<?php
/**
 * ContentUpdatePreview
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * The Selling Partner API for FBA inbound operations.
 *
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * OpenAPI spec version: 2024-03-20
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.61
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Luigel\AmazonSellingPartnerAPI\Models\FulfillmentInbound;

use \ArrayAccess;
use Luigel\AmazonSellingPartnerAPI\ObjectSerializer;

/**
 * ContentUpdatePreview Class Doc Comment
 *
 * @category Class
 * @description Preview of the changes that will be applied to the shipment.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ContentUpdatePreview implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ContentUpdatePreview';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'content_update_preview_id' => 'string',
        'expiration' => 'string',
        'requested_updates' => '\Luigel\AmazonSellingPartnerAPI\Models\FulfillmentInbound\RequestedUpdates',
        'transportation_option' => '\Luigel\AmazonSellingPartnerAPI\Models\FulfillmentInbound\TransportationOption'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'content_update_preview_id' => null,
        'expiration' => null,
        'requested_updates' => null,
        'transportation_option' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'content_update_preview_id' => 'contentUpdatePreviewId',
        'expiration' => 'expiration',
        'requested_updates' => 'requestedUpdates',
        'transportation_option' => 'transportationOption'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'content_update_preview_id' => 'setContentUpdatePreviewId',
        'expiration' => 'setExpiration',
        'requested_updates' => 'setRequestedUpdates',
        'transportation_option' => 'setTransportationOption'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'content_update_preview_id' => 'getContentUpdatePreviewId',
        'expiration' => 'getExpiration',
        'requested_updates' => 'getRequestedUpdates',
        'transportation_option' => 'getTransportationOption'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['content_update_preview_id'] = isset($data['content_update_preview_id']) ? $data['content_update_preview_id'] : null;
        $this->container['expiration'] = isset($data['expiration']) ? $data['expiration'] : null;
        $this->container['requested_updates'] = isset($data['requested_updates']) ? $data['requested_updates'] : null;
        $this->container['transportation_option'] = isset($data['transportation_option']) ? $data['transportation_option'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['content_update_preview_id'] === null) {
            $invalidProperties[] = "'content_update_preview_id' can't be null";
        }
        if ($this->container['expiration'] === null) {
            $invalidProperties[] = "'expiration' can't be null";
        }
        if ($this->container['requested_updates'] === null) {
            $invalidProperties[] = "'requested_updates' can't be null";
        }
        if ($this->container['transportation_option'] === null) {
            $invalidProperties[] = "'transportation_option' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets content_update_preview_id
     *
     * @return string
     */
    public function getContentUpdatePreviewId()
    {
        return $this->container['content_update_preview_id'];
    }

    /**
     * Sets content_update_preview_id
     *
     * @param string $content_update_preview_id Identifier of a content update preview.
     *
     * @return $this
     */
    public function setContentUpdatePreviewId($content_update_preview_id)
    {
        $this->container['content_update_preview_id'] = $content_update_preview_id;

        return $this;
    }

    /**
     * Gets expiration
     *
     * @return string
     */
    public function getExpiration()
    {
        return $this->container['expiration'];
    }

    /**
     * Sets expiration
     *
     * @param string $expiration The date in ISO 8601 format for when the content update expires.
     *
     * @return $this
     */
    public function setExpiration($expiration)
    {
        $this->container['expiration'] = $expiration;

        return $this;
    }

    /**
     * Gets requested_updates
     *
     * @return \Luigel\AmazonSellingPartnerAPI\Models\FulfillmentInbound\RequestedUpdates
     */
    public function getRequestedUpdates()
    {
        return $this->container['requested_updates'];
    }

    /**
     * Sets requested_updates
     *
     * @param \Luigel\AmazonSellingPartnerAPI\Models\FulfillmentInbound\RequestedUpdates $requested_updates requested_updates
     *
     * @return $this
     */
    public function setRequestedUpdates($requested_updates)
    {
        $this->container['requested_updates'] = $requested_updates;

        return $this;
    }

    /**
     * Gets transportation_option
     *
     * @return \Luigel\AmazonSellingPartnerAPI\Models\FulfillmentInbound\TransportationOption
     */
    public function getTransportationOption()
    {
        return $this->container['transportation_option'];
    }

    /**
     * Sets transportation_option
     *
     * @param \Luigel\AmazonSellingPartnerAPI\Models\FulfillmentInbound\TransportationOption $transportation_option transportation_option
     *
     * @return $this
     */
    public function setTransportationOption($transportation_option)
    {
        $this->container['transportation_option'] = $transportation_option;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
