<?php
/**
 * PackingOption
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * The Selling Partner API for FBA inbound operations.
 *
 * The Selling Partner API for Fulfillment By Amazon (FBA) Inbound. The FBA Inbound API enables building inbound workflows to create, manage, and send shipments into Amazon's fulfillment network. The API has interoperability with the Send-to-Amazon user interface.
 *
 * OpenAPI spec version: 2024-03-20
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.61
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Luigel\AmazonSellingPartnerAPI\Models\FulfillmentInbound;

use \ArrayAccess;
use Luigel\AmazonSellingPartnerAPI\ObjectSerializer;

/**
 * PackingOption Class Doc Comment
 *
 * @category Class
 * @description A packing option contains a set of pack groups plus additional information about the packing option, such as any discounts or fees if it&#x27;s selected.
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PackingOption implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'PackingOption';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'discounts' => '\Luigel\AmazonSellingPartnerAPI\Models\FulfillmentInbound\Incentive[]',
        'expiration' => '\DateTime',
        'fees' => '\Luigel\AmazonSellingPartnerAPI\Models\FulfillmentInbound\Incentive[]',
        'packing_groups' => 'string[]',
        'packing_option_id' => 'string',
        'status' => 'string',
        'supported_shipping_configurations' => '\Luigel\AmazonSellingPartnerAPI\Models\FulfillmentInbound\ShippingConfiguration[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'discounts' => null,
        'expiration' => 'date-time',
        'fees' => null,
        'packing_groups' => null,
        'packing_option_id' => null,
        'status' => null,
        'supported_shipping_configurations' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'discounts' => 'discounts',
        'expiration' => 'expiration',
        'fees' => 'fees',
        'packing_groups' => 'packingGroups',
        'packing_option_id' => 'packingOptionId',
        'status' => 'status',
        'supported_shipping_configurations' => 'supportedShippingConfigurations'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'discounts' => 'setDiscounts',
        'expiration' => 'setExpiration',
        'fees' => 'setFees',
        'packing_groups' => 'setPackingGroups',
        'packing_option_id' => 'setPackingOptionId',
        'status' => 'setStatus',
        'supported_shipping_configurations' => 'setSupportedShippingConfigurations'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'discounts' => 'getDiscounts',
        'expiration' => 'getExpiration',
        'fees' => 'getFees',
        'packing_groups' => 'getPackingGroups',
        'packing_option_id' => 'getPackingOptionId',
        'status' => 'getStatus',
        'supported_shipping_configurations' => 'getSupportedShippingConfigurations'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['discounts'] = isset($data['discounts']) ? $data['discounts'] : null;
        $this->container['expiration'] = isset($data['expiration']) ? $data['expiration'] : null;
        $this->container['fees'] = isset($data['fees']) ? $data['fees'] : null;
        $this->container['packing_groups'] = isset($data['packing_groups']) ? $data['packing_groups'] : null;
        $this->container['packing_option_id'] = isset($data['packing_option_id']) ? $data['packing_option_id'] : null;
        $this->container['status'] = isset($data['status']) ? $data['status'] : null;
        $this->container['supported_shipping_configurations'] = isset($data['supported_shipping_configurations']) ? $data['supported_shipping_configurations'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['discounts'] === null) {
            $invalidProperties[] = "'discounts' can't be null";
        }
        if ($this->container['fees'] === null) {
            $invalidProperties[] = "'fees' can't be null";
        }
        if ($this->container['packing_groups'] === null) {
            $invalidProperties[] = "'packing_groups' can't be null";
        }
        if ($this->container['packing_option_id'] === null) {
            $invalidProperties[] = "'packing_option_id' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['supported_shipping_configurations'] === null) {
            $invalidProperties[] = "'supported_shipping_configurations' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets discounts
     *
     * @return \Luigel\AmazonSellingPartnerAPI\Models\FulfillmentInbound\Incentive[]
     */
    public function getDiscounts()
    {
        return $this->container['discounts'];
    }

    /**
     * Sets discounts
     *
     * @param \Luigel\AmazonSellingPartnerAPI\Models\FulfillmentInbound\Incentive[] $discounts Discount for the offered option.
     *
     * @return $this
     */
    public function setDiscounts($discounts)
    {
        $this->container['discounts'] = $discounts;

        return $this;
    }

    /**
     * Gets expiration
     *
     * @return \DateTime
     */
    public function getExpiration()
    {
        return $this->container['expiration'];
    }

    /**
     * Sets expiration
     *
     * @param \DateTime $expiration The timestamp at which this packing option becomes no longer valid. This is based in ISO 8601 datetime with pattern `yyyy-MM-ddTHH:mm:ss.sssZ`.
     *
     * @return $this
     */
    public function setExpiration($expiration)
    {
        $this->container['expiration'] = $expiration;

        return $this;
    }

    /**
     * Gets fees
     *
     * @return \Luigel\AmazonSellingPartnerAPI\Models\FulfillmentInbound\Incentive[]
     */
    public function getFees()
    {
        return $this->container['fees'];
    }

    /**
     * Sets fees
     *
     * @param \Luigel\AmazonSellingPartnerAPI\Models\FulfillmentInbound\Incentive[] $fees Fee for the offered option.
     *
     * @return $this
     */
    public function setFees($fees)
    {
        $this->container['fees'] = $fees;

        return $this;
    }

    /**
     * Gets packing_groups
     *
     * @return string[]
     */
    public function getPackingGroups()
    {
        return $this->container['packing_groups'];
    }

    /**
     * Sets packing_groups
     *
     * @param string[] $packing_groups Packing group IDs.
     *
     * @return $this
     */
    public function setPackingGroups($packing_groups)
    {
        $this->container['packing_groups'] = $packing_groups;

        return $this;
    }

    /**
     * Gets packing_option_id
     *
     * @return string
     */
    public function getPackingOptionId()
    {
        return $this->container['packing_option_id'];
    }

    /**
     * Sets packing_option_id
     *
     * @param string $packing_option_id Identifier of a packing option.
     *
     * @return $this
     */
    public function setPackingOptionId($packing_option_id)
    {
        $this->container['packing_option_id'] = $packing_option_id;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status The status of the packing option. Can be: `OFFERED`, `ACCEPTED`, or `EXPIRED`.
     *
     * @return $this
     */
    public function setStatus($status)
    {
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets supported_shipping_configurations
     *
     * @return \Luigel\AmazonSellingPartnerAPI\Models\FulfillmentInbound\ShippingConfiguration[]
     */
    public function getSupportedShippingConfigurations()
    {
        return $this->container['supported_shipping_configurations'];
    }

    /**
     * Sets supported_shipping_configurations
     *
     * @param \Luigel\AmazonSellingPartnerAPI\Models\FulfillmentInbound\ShippingConfiguration[] $supported_shipping_configurations List of supported shipping modes.
     *
     * @return $this
     */
    public function setSupportedShippingConfigurations($supported_shipping_configurations)
    {
        $this->container['supported_shipping_configurations'] = $supported_shipping_configurations;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
